### ISSUE TITLE
Error While Making Devlopment Build

### ISSUE THREAD

**Issue by Bijit-Mondal** [TheNeuronProject/Neonclear#2]
Target: development
+----=+| DEMO BUILD |+=----+
[!] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)
    at Object.writeFileSync (node:fs:2150:5)
    at progress (/home/bijit/Desktop/Neonclear/node_modules/rollup-plugin-progress/dist/rollup-plugin-progress.js:28:8)
    at Object.<anonymous> (/home/bijit/Desktop/Neonclear/config/rollup.dev.js:73:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.require.extensions..js (/home/bijit/Desktop/Neonclear/node_modules/rollup/bin/rollup:2914:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/bijit/Desktop/Neonclear/node_modules/rollup/bin/rollup:2921:32

**Comment by ClassicOldSong** [comment]
This project is almost abandoned 
Please try something else 
Sorry for that!
